loom_mode=remap
minecraft_version=1.21.3
loader_version=0.18.4
fabric_api_version=0.114.1+1.21.3
fabric_loader_dependency=>=0.18.4
minecraft_dependency=~1.21.3
java_min_version=21
java_release=21
source_profile=1.21.4
